### ISSUE TITLE
Redundant step at entropy source init

### ISSUE THREAD

**Issue by ktaborowski** [Abhayakara/mdnsresponder#15]
https://github.com/Abhayakara/mdnsresponder/blob/50902620f335639ffc86d0bc41c101e684390f70/ServiceRegistration/sign-mbedtls.c#L146-L147
I think the `mbedtls_entropy_init` already calls `mbedtls_entropy_add_source` 
https://github.com/ARMmbed/mbedtls/blob/8a129828da57b34563618e0a957a5b1bedf4c67f/library/entropy.c#L89

**Comment by Abhayakara** [comment]
While this observation is true, the "get entropy" function is different. I'm not sure this matters, but I don't know of an easy way to find out, and I think this is at worst harmless.
