### ISSUE TITLE
Update Lease Option: spec and impl not consistent

### ISSUE THREAD

**Issue by wgtdkp** [Abhayakara/mdnsresponder#5]
Hi, got an issue about the Update Lease Option:

[Section 4](https://tools.ietf.org/html/draft-sekar-dns-ul-02#section-4) of `Dynamic DNS Update Leases draft-sekar-dns-ul-02` Requires the `CLASS` and `TTL` of the `Update Lease Option` to be zero, but the implementation is not doing so:

The spec:
```txt
The OPT RR is formatted as follows:

    Field Name      Field Type    Description
    ----------------------------------------------------------------
    NAME            domain name   empty (root domain)
    TYPE            u_int16_t     OPT
    CLASS           u_int16_t     0
    TTL             u_int32_t     0
    RDLEN           u_int16_t     describes RDATA
    RDATA           byte stream   (see below)
```

The implementation:
https://github.com/Abhayakara/mdnsresponder/blob/50902620f335639ffc86d0bc41c101e684390f70/ServiceRegistration/srp-client.c#L1307

https://github.com/Abhayakara/mdnsresponder/blob/50902620f335639ffc86d0bc41c101e684390f70/ServiceRegistration/towire.c#L450-L467

Not sure whether the spec or the impl is the desired behavior.

**Comment by Abhayakara** [comment]
draft-sekar is wrong (mostly in the sense of specifying something that is already specified in detail elsewhere). Take a look at [RFC6891](https://tools.ietf.org/html/rfc6891)
