### ISSUE TITLE
SRP registration in the network data can be delayed after a power cycle.

### ISSUE THREAD

**Issue by ndyck14** [Abhayakara/mdnsresponder#9]
We often observe delay in SRP re-registering after a power cycle. Note our BR does not currently keep the same RLOC16 through power cycle, and given issue #8 this might be a co-factor.

Our testing on in-market devices shows that they pick up RLOC16 from before power cycle, sometimes with a delay of a few seconds after attaching. I don’t think that’s required behaviour by spec, so it would be helpful if this should be a required component to make this approach viable when standardized.

**Comment by Abhayakara** [comment]
There are two possibilities for delay on re-registering. One is that the SRP server will in fact wait for some period of time before advertising, but this should not be long. The other is that the way Thread network data propagates, there may be delays and out-of-date information. The design of the daemon takes this into account—we expect things to settle out. However, in some cases the thread management code will detect what looks like a partition and wait an hour for things to settle before de-registering a redundant SRP service.

This is all expected to change anyway when we implement the anycast SRP support.
